### ISSUE TITLE
We should avoid patterns that deparse substitute/quote an injected character to get said character

### ISSUE THREAD

**Issue by Laksafoss** [Laksafoss/EpiForsk#16]
Patterns like
`stringr::str_sub(deparse(quote({{ function_input_in_character_format }})), 2)`
and
`gsub('"', "", stringr::str_sub(deparse(quote({{ function_input_in_character_format }})), 2))`
are commen in `aso_freq_function`. These should be avoided, as they are unnecessarily clumsy, hard to read, and can be made much simpler.

Consider the following two functions 

```
foo <- function(var1) {
    data.frame(x = 1:3) |>
        dplyr::mutate(
            new = gsub('"', "", stringr::str_sub(deparse(quote({{ var1 }})), 2))
        )
}
```
and
```
bar <- function(var1) {
    data.frame(x = 1:3) |>
        dplyr::mutate(
            new = var1
        )
}
```

The calls
```
foo("x")
bar("x")
```
produce the same output!

**Comment by Laksafoss** [comment]
Moreover, the following should be avoided:

You write 
```
# Getting name of original Variable1 as a string (to be used below)
  Orig_var1_name <- gsub(
    '"',
    "",
    paste(deparse(substitute(var1)), collapse = "")
  )
```
and then when you need to assign a column `Orig_var1_name` as a name you write
```
# Setting the name of the first variable correctly
    colnames(func_table10)[1] <- noquote(Orig_var1_name)
```
This is needlessly complicated.

**Comment by kjakobse** [comment]
removed patterns in 3327021f708c0e445d6f6390b4b92fad51590195
