### ISSUE TITLE
We sould avoid joins with implicit `by`

### ISSUE THREAD

**Issue by Laksafoss** [Laksafoss/EpiForsk#18]
In `aso_freq_function()` there are many
```
suppressMessages(dplyr::full_join(func_table22_1, func_table22_2))
```
I think that `suppressMessages()` should be avoided here and a `by` term should be given in the join instead.

**Comment by kjakobse** [comment]
explicit joins added in 5f68b3f47310ec5b99258d56e5d2d6162ce5da2a
