### ISSUE TITLE
Avoid using double curly brackets when they have no effect 

### ISSUE THREAD

**Issue by Laksafoss** [Laksafoss/EpiForsk#21]
Patterns like 
```
func_table25 <- dplyr::full_join(
        func_table22,
        chi_p,
        by = c({{ by_vars }}, Orig_var1_name)
      )
```
are common in `aso_freq_function()`. But the following code will produce the exact same output
```
func_table25 <- dplyr::full_join(
        func_table22,
        chi_p,
        by = c(by_vars, Orig_var1_name)
      )
```

**Comment by kjakobse** [comment]
Removed embrace from joins in ce8b66a3574ad35d6b7456f08cc049a0601a9657, and from all_of in 94149442c2f28ba75db253184b24ee2a45ae1ce9.
